services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--http_port 8222"

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NATS_URL=nats://nats:4222
      - RUST_LOG=debug
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    depends_on:
      - nats

  test-publisher:
    image: golang:1.21
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    command: >
      sh -c "go install github.com/nats-io/natscli/nats@latest &&
             while true; do
               nats pub test.hello 'Hello' || true;
               nats pub test.time \"$$(date)\" || true;
               nats pub test.random \"$$(echo $$RANDOM)\" || true;
               sleep 2;
             done"

volumes:
  cargo-cache:
  target-cache: